language: c
# For doc-building dependencies.
cache: pip
  
addons:
  apt:
    packages:
      - tk-dev
      - liblzma-dev
      - python-pip
      
matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - PYTHON=python
    - os: linux
      compiler: clang
      env:
        - PYTHON=python
    - os: osx
      compiler: clang  # gcc is just a symlink for clang.
      env:
        - PYTHON=python.exe
    - os: linux
      language: python
      python: 3.5
      before_script:
        - cd Doc
        - make venv PYTHON=python3
      script:
        - make html SPHINXBUILD="./venv/bin/python3 -m sphinx" SPHINXOPTS="-nW -q -b linkcheck"

before_script:
  - ./configure --with-pydebug
  - make -j4

script:
  - ./$PYTHON -bb -E -W default -m test -r -w -uall -j8

notifications:
  email: false
